### ISSUE TITLE
Bughunting: mjsunit/asm/int32div

### ISSUE THREAD

**Issue by ilijapavlovic** [v8mips/v8mips#514]
The test fails on MIPS64 big endian in Debug mode:
https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge/builds/2172/steps/Check/logs/int32div

**Comment by ilijapavlovic** [comment]
The problem locally reproduced:
```
#
# Fatal error in ../../src/compiler/new-escape-analysis.h, line 123
# Debug check failed: offset % kPointerSize == 0.
#
```

**Comment by ilijapavlovic** [comment]
For the 1st time, this error is caused with CL
```
40a9eabc44204c353dce4bec08e8bd87b3fc0cc7 Reland "[turbofan] enable new implementation of escape analysis"
```
The problem was corrected with reverting mentioned CL and with a fix for compilation failure on big-endian:
```
943651b789f8757fd86f133b606eb7d2a86bcc1b Revert "Reland "[turbofan] enable new implementation of escape analysis""
+
46c89e66a67895d970b468b84268bc8bb450139d Fix compilation failure on big-endian
```
The final problem is caused with new version of Reland "[turbofan] enable new implementation of escape analysis"
```
66d31d19c40c66222c959f4b132cdba0739ce6ed Reland "[turbofan] enable new implementation of escape analysis"
```
Reviewed-on: https://chromium-review.googlesource.com/603788

The check `DCHECK(offset % kPointerSize == 0);` fails for following values:
```
(gdb) print offset             
$92 = 12
(gdb) print kPointerSize
$93 = 8
```

**Comment by ilijapavlovic** [comment]
New escape analysis is introduced with following CL:
```
commit d230b44f0c5a26c5f7eaff9663139cb7ca50294c
Author: Tobias Tebbi <tebbi@chromium.org>
Date:   Fri Jul 28 13:13:44 2017 +0200

    [turbofan] staging new implementation of escape analysis
    
    Bug:
    Change-Id: Idebe4fa6d651a404a0dc1947ed4a34a8dc9707a9
    Reviewed-on: https://chromium-review.googlesource.com/565720
    Commit-Queue: Tobias Tebbi <tebbi@chromium.org>
    Reviewed-by: Jaroslav Sevcik <jarin@chromium.org>
    Cr-Commit-Position: refs/heads/master@{#46966}
```
